Move the groovy-json dep into the api provided by the library
This seems to be required to solve an exception occuring when the internal data structure of the JsonMedia is empty

The exception:
java.lang.IllegalAccessError: tried to access field groovy.json.JsonOutput.EMPTY_LIST_CHARS from class groovy.json.DefaultJsonGenerator